### ISSUE TITLE
Use of tinytex in the vignette breaks 'R CMD build' on machines with MiKTeX

### ISSUE THREAD

**Issue by hpages** [Accio/KEGGgraph#11]
Hi @Accio,

Sorry to bother you again but our daily builds indicate a vignette error on Windows for the latest version of **KEGGgraph**:

- https://bioconductor.org/checkResults/3.16/bioc-LATEST/KEGGgraph/palomino4-buildsrc.html
- https://bioconductor.org/checkResults/3.17/bioc-LATEST/KEGGgraph/palomino3-buildsrc.html

The error seems to be related to the use of `tinytex::parse_install()` by the vignette, which fails because TeX Live is not installed on the machine (we have MiKTeX on our Windows builders, not TeX Live).

I'm not familiar with the **tinytex** package but I'm surprised that it would introduce such requirement. Unless there's a way to make **tinytex** work with MiKTeX, I'm afraid that such requirement means that the package is not cross-platform compatible, which makes it unfit for the task.

Is there another way to achieve whatever it is that you are trying to achieve, that does not use **tinytex**?

Don't hesitate to ask on the bioc-devel mailing list if you have questions or concerns about this.

Thanks again for your contribution to Bioconductor.

Best,
H.

**Comment by Accio** [comment]
thanks @hpages, I will take a look at it as soon as possible.

**Comment by Accio** [comment]
hi @hpages, the issue should be solved in [616dd2a](https://github.com/Accio/KEGGgraph/commit/616dd2a46f5e07a235e2ec22daf166be3c80dbe4). If not please kindly let me know. Thank you for pointing the issue out. Best regards, D.

**Comment by hpages** [comment]
That seems to have solved the problem, thanks!
