### ISSUE TITLE
SSL peer certificate or SSH remote key was not ok Error

### ISSUE THREAD

**Issue by jordlang01** [Accio/KEGGgraph#13]
Hello,

Over the past couple of days, I've been getting the error below when trying to download a KEGG pathway:

trying URL 'https://rest.kegg.jp/get/mmu04670/kgml'
Error in download.file(url, destfile = tmp) : 
  cannot open URL 'https://rest.kegg.jp/get/mmu04670/kgml'
In addition: Warning message:
In download.file(url, destfile = tmp) :
  URL 'https://rest.kegg.jp/get/mmu04670/kgml': status was 'SSL peer certificate or SSH remote key was not OK'

Specifically it says that the ;status was 'SSL peer certificate or SSH remote key was not OK'. I'm unsure what that means. Any advice would be much appreciated. I even get this error when I run the example below in the getKGMLurl documentation:

asConnection <- RCurl::url.exists(getKGMLurl("cel00010"))
if(hasConnection) {
  tmp <- tempfile()
  retrieveKGML(pathwayid='00010', organism='cel', destfile=tmp, method="auto")
} else {
  warnings("No connection to KEGG webservice")
}

The error is:

Warning message:
In download.file(url, destfile = tmp) :
  URL 'https://rest.kegg.jp/get/mmu04670/kgml': status was 'SSL peer certificate or SSH remote key was not OK' 
No connection to KEGG webservice

Thank you,
Jordan

**Comment by Accio** [comment]
Private communication: problem was raised by a new version of R, reinstalling the old version solved the issue. The issue is closed. Thank you for reporting it, @jordlang01
