### ISSUE TITLE
Failure to download KEGG pathways when using pathfindR

### ISSUE THREAD

**Issue by apelin20** [Accio/KEGGgraph#6]
Hello,

I am trying to use pathfindR which relies on KEGGgraph for KEGG pathway download and mapping, but I am getting these odd errors:

`Downloading pathway diagrams of 286 KEGG pathways

  |                                                                      |   0%Cannot retrieve PNG url: hsa03010
Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
Here's the original error message:
'url' must be a length-one character vector
Cannot retrieve PNG url: hsa05171
Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
Here's the original error message:
'url' must be a length-one character vector
  |                                                                      |   1%Cannot retrieve PNG url: hsa03040
Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
Here's the original error message:
'url' must be a length-one character vector
  |=                                                                     |   1%Cannot retrieve PNG url: hsa04141
Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
Here's the original error message:
'url' must be a length-one character vector
Cannot retrieve PNG url: hsa05012
Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
Here's the original error message:
'url' must be a length-one character vector
  |=                                                                     |   2%Cannot retrieve PNG url: hsa05020
Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
`

I was wondering if this is because of a recent change in KEGG urls?

Thanks

**Comment by Accio** [comment]
thanks for reporting, @apelin20! This is new to me. Do you mind attaching a minimal reproducible example so that I can check it as well? Thanks and best regards, David

**Comment by apelin20** [comment]
Thanks for getting back to me Accio. This got resolved with KEGGREST - https://github.com/Bioconductor/KEGGREST/issues/12

The trick was to use install_github("Bioconductor/KEGGREST")

**Comment by Accio** [comment]
Thanks for the update!
